version: '2'

services:

  ############################
  ##### Identity Service #####
  ############################
 
  identity-service:
    image: nimbleplatform/identity-service:latest
    env_file:
      - env_vars
      - env_vars-prod  # stores secretes and deployment specific information on the host machine.
      - platform-config
    environment:
      - _JAVA_OPTIONS=-Xmx768m -Xms50m
    ports:
      - "9096:9096"
    networks:
      - infra

  ##############################
  ## Business Process Service ##
  ##############################

  business-process-service:
    image: nimbleplatform/business-process-service:latest
    env_file:
      - env_vars
      - env_vars-prod  # stores secretes and deployment specific information on the host machine.
      - platform-config
    environment:
      - _JAVA_OPTIONS=-Xmx1536m -Xms50m
    ports:
      - "8085:8085"
    networks:
      - infra

  ##############################
  ####### Catalog Service ######  
  ##############################
  
  catalog-service-srdc:
    image: nimbleplatform/catalogue-service-micro:latest
    ports:
      - "10095:8095"
    env_file:
      - env_vars
      - env_vars-prod  # stores secretes and deployment specific information on the host machine.
      - platform-config
    environment:
      - _JAVA_OPTIONS=-Xmx1536m -Xms50m
    networks:
      - infra

  ##############################
  ####### Indexing Service #####
  ##############################

  indexing-service:
    image: nimbleplatform/indexing-service:latest
    ports:
      - "9101:8080"
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms50m
      - SOLR_HOST=http://solr:8983/solr/
    mem_limit: 1000m
    env_file:
      - env_vars
      - env_vars-prod
      - platform-config
    networks:
      - infra

  ##############################
  ####### Search Service #######
  ##############################

  search-service:
    image: nimbleplatform/catalog-search-service:latest
    restart: always
    ports:
      - "10096:8090"
    env_file:
      - env_vars
      - platform-config
    environment:
      - "SPRING_PROFILES_ACTIVE=productive"
      - "MARMOTTA_URL=https://nimble-platform.salzburgresearch.at/marmotta"
      - "LANGUAGE_LABEL=http://www.w3.org/2004/02/skos/core#prefLabel"
      - "CATALOG_SEARCH_CONFIG:/resources/sqpConfiguration-productive.xml"
      - "_JAVA_OPTIONS=-Xmx256m -Xms50m"
    mem_limit: 1000m
    networks:
      - infra

  ###############################
  ###### Frontend Service #######
  ###############################
  
  frontend-service:
    image: nimbleplatform/frontend-service:latest
    ports:
      - "9092:8080"
    env_file:
      - env_vars
      - env_vars-prod
      - platform-config
    environment:
      _JAVA_OPTIONS: -Xmx512m -Xms50m
    networks:
      - infra
  
  frontend-service-sidecar:
    image: nimbleplatform/sidecar:latest
    ports:
      - "9097:9097"
    env_file:
      - env_vars
      - env_vars-prod
      - platform-config
    environment:
      SIDECAR_NAME: frontend-service
      SIDECAR_APP_HOST: frontend-service
      SIDECAR_APP_PORT: 8080 # use internal port of network (not publicly exposed)
      SIDECAR_APP_HEALTH_URI: http://frontend-service:8080/health.json
      SIDECAR_APP_HOMEPAGE_URI: http://frontend-service:8080/
      _JAVA_OPTIONS: -Xmx768m -Xms50m
    networks:
      - infra

  ###############################
  #### Data Channel Service #####
  ###############################

  data-channel-service:
    image: nimbleplatform/data-channel-service:latest
    restart: always
    env_file:
      - env_vars
      - env_vars-prod
      - platform-config
    environment:
      _JAVA_OPTIONS: -Xmx768m -Xms50m
    ports:
      - "9099:9099"
    networks:
      - infra

  ###############################
  ######### Data Pipes ##########
  ###############################

  data-pipes:
    image: nimbleplatform/data-pipes:latest
    env_file:
      - env_vars
      - env_vars-prod
      - platform-config
    environment:
      _JAVA_OPTIONS: -Xmx256m -Xms50m
    mem_limit: 500m
    ports:
      - "8082:8080"
    networks:
      - infra

  ###############################
  ## Tracking Analysis Service ##
  ###############################

  tracking-analysis-service:
    image: nimbleplatform/tracking-analysis-service:latest
    restart: always
    env_file:
      - env_vars
      - env_vars-prod
      - platform-config
    environment:
      _JAVA_OPTIONS: -Xmx128m -Xms50m
    mem_limit: 400m
    ports:
      - "9100:9100"
    networks:
      - infra

  ###############################
  ## Data Aggregation Service ###
  ###############################

  data-aggregation-service:
    image: nimbleplatform/data-aggregation-service:latest
    restart: always
    env_file:
      - env_vars
      - env_vars-prod
      - platform-config
    environment:
      _JAVA_OPTIONS: -Xmx64m -Xms50m
    networks:
      - infra

  ###############################
  ######## Trust Service ########
  ###############################

  trust-service:
    image: nimbleplatform/trust-service:latest
    restart: always
    env_file:
      - env_vars
      - env_vars-prod
      - platform-config
    environment:
      PORT: 9098
      _JAVA_OPTIONS: -Xmx128m -Xms50m
    mem_limit: 800m
    ports:
      - "9098:9098"
    networks:
      - infra

networks:
  infra:
    external:
      name: nimbleinfraprod_default
