kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name:  jenkins-persistent-volume-claim
spec:
  storageClassName: class-nfs
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      type: type-nfs
