apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: jenkins-master
  name: jenkins-master
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: jenkins-master
    spec:
      containers:
        - image: nimbleplatform/jenkins-master:iasset
          name: jenkins-master
          env:
            - name: JENKINS_OPTS
              value: '"--prefix=/jenkins/"'
          ports:
            - containerPort: 8080
            - containerPort: 50000
          resources: {}
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /var/jenkins_home
              name: jenkins-master-claim0
            - mountPath: /var/run/docker.sock
              name: jenkins-master-claim2
              subPath: docker.sock
      restartPolicy: Always
      volumes:
        - name: jenkins-master-claim0
          persistentVolumeClaim:
            claimName: jenkins-pv-claim
        - name: jenkins-master-claim2
          hostPath:
            path: /var/run
