kind: PersistentVolume
apiVersion: v1
metadata:
  name: jenkins-persistent-volume
  labels:
    type: type-nfs
spec:
  storageClassName: class-nfs
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /opt/jenkins.persistent
