version: '2'

services:
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/certs:ro
      - ./htpasswd:/etc/nginx/htpasswd:ro
    expose:
      - "8080"
    ports:
      - "8080:8080"
      - "443:443"
      - "5601:5601"
    networks:
      - nimble-cloud-infra
      - jenkins


networks:
  nimble-cloud-infra:
    external:
      name: nimbleinfraprod_default
  jenkins:
    external:
      name: jenkins_default
