version: '3'

services:
  ##############################
  ####### Indexing Service #####
  ##############################

  indexing-service:
    image: nimbleplatform/indexing-service:staging
    ports:
      - "9101:8080"
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms50m
      - SOLR_HOST=http://solr:8983/solr/
      #    mem_limit: 1000m
    env_file:
      - env_vars
    networks:
      - efactory-network

networks:
  efactory-network:
    external:
      name: security-network
