version: '2'

services:
  ##########################
  #### MS Infrastructure ###
  ##########################

  config-server:
    image: nimbleplatform/config-server:latest
    env_file:
      - env_vars
    ports:
      - "8888:8888"
    environment:
      _JAVA_OPTIONS: -Xmx256m -Xms50m
    networks:
      - efactory-network

  service-discovery:
    image: nimbleplatform/service-discovery:latest
    env_file:
      - env_vars
    ports:
      - "8761:8761"
    depends_on:
      - config-server
    environment:
      _JAVA_OPTIONS: -Xmx256m -Xms50m
    networks:
      - efactory-network

  gateway-proxy:
    image: nimbleplatform/gateway-proxy:latest
    env_file:
      - env_vars
        #    ports:
      #      - "80:80"
    depends_on:
      - config-server
      - service-discovery
    environment:
      _JAVA_OPTIONS: -Xmx128m -Xms50m
    networks:
      - efactory-network

  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    networks:
      - efactory-network

  efackeycloak:
    image: jboss/keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: 1qaz2wsx
      PROXY_ADDRESS_FORWARDING: "true"
      JDBC_PARAMS: "ssl=false"
    ports:
      - 10096:9990
      - 10097:8443
    depends_on:
      - postgres
    networks:
      - efactory-network

  apisix:
    build: ./apisix
    restart: always
    volumes:
      - ./apisix/apisix_log:/usr/local/apisix/logs
      - ./apisix/config.yaml:/usr/local/apisix/conf/config.yaml:ro
    depends_on:
      - etcd
    ports:
      - 9080:9080
      - 9443:9443
    networks:
      - efactory-network


  etcd:
    image: gcr.io/etcd-development/etcd:v3.3.12
    command: /usr/local/bin/etcd --advertise-client-urls http://0.0.0.0:2379 --listen-client-urls http://0.0.0.0:2379
    restart: always
    volumes:
      - ./etcd_data:/etcd_data
    environment:
      ETCD_DATA_DIR: /etcd_data
    ports:
      - "127.0.0.1:2379:2379/tcp"
    networks:
      - efactory-network

volumes:
  postgres_data:

networks:
  efactory-network:
    external:
      name: security-network
